backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

publish_mode: simple
local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Description", name: "hero_description", widget: "text"}
          - {label: "About Us", name: "about_us", widget: "markdown"}
      
      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
